# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quantity_left', models.IntegerField(default=0)),
            ],
        ),
    ]
