# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_inter_part', models.IntegerField(default=0)),
                ('ms_serial_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipmenttool',
            name='tool_quantity_left',
            field=models.IntegerField(default=0),
        ),
    ]
