# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0002_auto_20170310_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_tools',
            field=models.ManyToManyField(to='PM.EquipmentTool'),
        ),
    ]
