# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0004_checklist_dailyreport_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_location', models.CharField(max_length=50)),
                ('sc_desc', models.CharField(max_length=100)),
                ('sc_brand_name', models.CharField(max_length=50)),
                ('sc_inspection_date', models.DateField()),
                ('sc_inspection_by', models.CharField(max_length=50)),
                ('sc_next_inspection_date', models.DateField()),
                ('sc_condition', models.CharField(max_length=50)),
                ('sc_comment', models.CharField(max_length=200)),
                ('sc_date', models.DateField()),
            ],
        ),
    ]
