# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0005_safetycheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'permissions': (('view_CheckList', 'Can view CheckList'),)},
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'permissions': (('view_DailyReport', 'Can view daily report'),)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('view_Order', 'Can view orders'),)},
        ),
        migrations.AlterModelOptions(
            name='safetycheck',
            options={'permissions': (('view_SafetyCheck', 'Can view safety check'),)},
        ),
    ]
