# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0007_auto_20170327_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ord_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
