# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0008_auto_20170328_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ord_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
