# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0010_auto_20170328_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_complete',
            field=models.BooleanField(default=False),
        ),
    ]
