# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0011_order_ord_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='ms_tools',
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_cons_name',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_cons_qty',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_form_content',
            field=models.CharField(default='a', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_form_fields',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_form_names',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_form_reqs',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_tools_name',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_tools_qty',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='ms_inter_part',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='ms_serial_num',
            field=models.CharField(max_length=100),
        ),
    ]
