# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0012_auto_20170402_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_content', models.CharField(max_length=2000)),
                ('mc_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='ms_form_content',
        ),
        migrations.AddField(
            model_name='maintenancecontent',
            name='mc_temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.MaintenanceSchedule'),
        ),
    ]
