# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0014_maintenanceschedule_ms_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='eq_add_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_last_main_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancecontent',
            name='mc_last_main_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
