# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0015_auto_20170404_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='ms_cons_name',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='ms_cons_qty',
        ),
    ]
