# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0017_auto_20170408_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ms_maintenance_schedule',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_maintenance_schedule',
            field=models.IntegerField(default=1),
        ),
    ]
