# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0019_auto_20170408_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancecontent',
            name='mc_last_main_date',
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='mc_last_main_date',
            field=models.DateField(null=True),
        ),
    ]
