# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0021_auto_20170408_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='mc_next_main_date',
            field=models.DateField(null=True),
        ),
    ]
