# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0023_auto_20170409_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='dp_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
