# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0024_auto_20170410_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='eq_tools_name',
            field=models.CharField(default='None', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_tools_qty',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ord_tools_name',
            field=models.CharField(default='None', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ord_tools_qty',
            field=models.CharField(default='None', max_length=500),
            preserve_default=False,
        ),
    ]
