# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0025_auto_20170414_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_serial_num',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
