# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0029_maintenancecontent_mc_main_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecontent',
            name='mc_complete',
            field=models.BooleanField(default=False),
        ),
    ]
