# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0032_auto_20170426_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ord_assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
