# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0034_auto_20170429_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ord_date_issue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
