# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0035_auto_20170502_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ord_building',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_supervisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_work_ord',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_work_req',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
